jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout workflow
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        ORG_GRADLE_PROJECT_version: ${{ inputs.version }}
      name: Execute Gradle publish
      uses: gradle/gradle-build-action@v2
      with:
        arguments: printVersion publishPlugins
        build-root-directory: build\typescript-generator-gradle-plugin-publisher
        gradle-version: 7.5.1
name: Release to Gradle plugin portal
on:
  repository_dispatch:
    types: trigger-ga___release-gradle-plugin.yml
