jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout workflow
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      name: Setup GPG signing key
      run: "if (-not $env:GPG_SIGNING_KEY) {\n  Write-Error \"Please set GPG_SIGNING_KEY\
        \ environment variable\"\n  exit 1\n}\nmkdir target -Force | Out-Null\n$gpg_signing_key\
        \ = [Convert]::FromBase64String($env:GPG_SIGNING_KEY)\n[System.IO.File]::WriteAllBytes(\"\
        target/gpg_signing_key.bin\", $gpg_signing_key)\ngpg --import target/gpg_signing_key.bin\n\
        gpg --list-secret-keys\n"
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Sign and upload
      run: './build/release-build.ps1

        '
name: Release to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release.yml
